### ISSUE TITLE
How to calculate fee with tx size?

### ISSUE THREAD

**Issue by mgpai22** [cmdruid/tapscript#1]
How to get the byte count or vSize of a transaction in order to accurately calculate an adequate fee?

**Comment by cmdruid** [comment]
Hello. I just updated the library to version 1.2.8. There is now a `Tx.getTxSize(txdata)` method which will return an object with all the various sizes (base size, vsize, weight, etc.)

Let me know if that works for you!

**Comment by mgpai22** [comment]
Awesome! Thank you for the swift update
