### ISSUE TITLE
`Tx.encode` fail for file larger than 260 byte

### ISSUE THREAD

**Issue by satoshiman** [cmdruid/tapscript#14]
I have tried to inscribe file has size < 260b successfully according to the example, but for files larger than 260b it seems that encoding tx is having problems. it seems the 520 byte limit is misdefined leading to the wrong encoding (personally)

**Comment by cmdruid** [comment]
I apologize for the delay. This should be fixed in 1.4.3. Please feel free to re-open this issue if you are still having the same problem in the new version.
