### ISSUE TITLE
witness problem

### ISSUE THREAD

**Issue by 216kedi** [cmdruid/tapscript#18]
I performed a sats token mint transaction using the go-ord-tx repository without much knowledge. I did not know that the mempool limit was 25. My transaction was approved, but the script did not execute after 25 transactions. How can I make the utxos at the tahhahut address execute the script using this library? I'm having trouble creating the 1st and 3rd witness values. I'm just starting to learn. Can you help me?

**Comment by cmdruid** [comment]
I'm not familiar with the `go-ord-tx` library. If you have the private key that spends the output, and if you have the file and other needed data to recreate the reveal tx, then you can create it manually using this library and then use a bitcoin node or other API to broadcast the tx. I hope that helps.
