### ISSUE TITLE
Larger witness data (ordinal inscription) lead to OP_SUCCESSx rejection

### ISSUE THREAD

**Issue by BennyTheDev** [cmdruid/tapscript#19]
In the latest version, creating inscriptions leads to push rejections on OP_SUCCESSx (tested in browser).
Version 1.2.7 works normally.

Script.decode() on the raw tx errors as well (string length exceeded).

Sample asm from bitcoin-cli decodescript:

<img width="1831" alt="image" src="https://github.com/cmdruid/tapscript/assets/1433403/e7fd9f35-6b25-4aea-9c7a-7850eadce75b">

**Comment by cmdruid** [comment]
I will take a look at this. It looks like it may be a simple parsing error.

**Comment by cmdruid** [comment]
I apologize, I have not had the time to take a look into this. I am working on meeting a deadline at the end of this month.

I should have more time beginning of next month.  There's a new version of tapscript ready to release, just need to update the documentation.

**Comment by rohitkeshav27** [comment]
Hey man 
Got this error 

**non-mandatory-script-verify-flag (OP_SUCCESSx reserved for soft-fork upgrades)**

**Comment by cmdruid** [comment]
I apologize for the delay. This should be fixed in 1.4.3. Please feel free to re-open this issue if you are still having the same problem in the new version.
