### ISSUE TITLE
crypto.getRandomValues must be defined node js error

### ISSUE THREAD

**Issue by mgpai22** [cmdruid/tapscript#2]
Hello I get the following error in node js:

```
/@cmdcode/tapscript/dist/module.js:104
    throw new Error('crypto.getRandomValues must be defined');
```

As a local work around I changed (line 56 in module.js)
```
const crypto$2 = typeof globalThis === 'object' && 'crypto' in globalThis ? globalThis.crypto : undefined;
```
to 
```
import * as crypto$2  from 'crypto';
```

**Comment by cmdruid** [comment]
What version of nodejs are you running? I believe you need version 19 or above for the new globalThis object to work.

**Comment by mgpai22** [comment]
Yes I was running and older version, node 19+ works great!
