### ISSUE TITLE
crypto is not defined

### ISSUE THREAD

**Issue by rohitkeshav27** [cmdruid/tapscript#21]
I keep getting this error 
I dont want to use patch-package (by making changes to the file)

Is there any other easier way to solve this error?
Please do reply fast!!

![image](https://github.com/cmdruid/tapscript/assets/43274184/aea7f129-0147-41dc-b56a-d514bb79d267)

**Comment by cmdruid** [comment]
What version of nodejs are you using? Try upgrading to v19.

**Comment by rohitkeshav27** [comment]
Oh yeah !
That was the issue !
I updated the Nodejs version  , and it solved the issue

Thanks for the prompt reply !!
