### ISSUE TITLE
Plz how to inscribe brc20?

### ISSUE THREAD

**Issue by winktool** [cmdruid/tapscript#3]

**Comment by winktool** [comment]
Thanks a lot

**Comment by winktool** [comment]
How can I inscribe a BRC20 from wallet A to wallet B and is there a specific example of the various inputs and outputs? I would like to see more comments, thank you very much.

**Comment by cmdruid** [comment]
I'm not familiar with the BRC-20 protocol myself sorry. I think the official repository is here, but I don't know for sure: https://github.com/bitcoin-computer/monorepo/tree/main/packages/BRC20

**Comment by winktool** [comment]
Well,and how to use wallet in testnet?
|https://github.com/cmdruid/tapscript/blob/4681c6fd5264c9c5af63227f262e84420b6fb71b/test/example/taproot/inscribe.test.ts#L33

**Comment by cmdruid** [comment]
You don't have to change the key cryptography when using testnet or any other network.
