### ISSUE TITLE
Add Metadata to inscription

### ISSUE THREAD

**Issue by MarshmallowCrypto** [cmdruid/tapscript#32]
Hey, is there any way to add metadata to the inscriptions when inscribing? Like it's done in the docs here https://docs.ordinals.com/inscriptions/metadata.html

**Comment by cliobitcoinbank** [comment]
Yes the features in the docs are implemented and working. You can use --json-metadata <JSON_METADATA> or --cbor-metadata <CBOR_METADATA> to add metadata to an ordinal.
