### ISSUE TITLE
Add multiple parent to a child inscription

### ISSUE THREAD

**Issue by rohitkeshav27** [cmdruid/tapscript#36]
I was trying to add multiple parent to a child inscription .
So , according the the "Ordinal Theory Handbook" ,

![image](https://github.com/cmdruid/tapscript/assets/43274184/1aad71b5-acb0-4958-a8ba-67b6626da89f)

I follow the first 2 points .According to the second bullet point I spend both parent inscription as first 2 inputs , and the creation of the child inscription is the 3rd input.

But my doubt is in the 3rd bullet point , Which serialised binary inscription ID should I include in the tag 3 the first parent's or the seconds , if i have to add both how do i do it?

According to @cmdcode/tapscript , how will I include 2 parent serialised binary inscription ids whiie designing the script manually

**Comment by cmdruid** [comment]
I'm looking here for reference:

> https://docs.ordinals.com/inscriptions/provenance.html

I don't see anything that let's you specify multiple parents for a child inscription. Are you sure that it is possible? Is there another transaction that does this, that you can provide as a reference?

**Comment by rohitkeshav27** [comment]
Hey , yeah it is possible 

https://testnet.ordinals.com/inscription/5e45e79efae3780eb70d4f50b84611e5cde96fd7693886c6f30d9efffd913ac2i0

Look into the above link , I could create them.
So basically we add 2 OP_RETURN 3 , and pass the serialised binary Inscription ID of the parents to be included!
