### ISSUE TITLE
OP_RETURN in output

### ISSUE THREAD

**Issue by skyrover7** [cmdruid/tapscript#38]
@cmdruid was trying to implement the runes specification on my existing codebase used for inscriptions. 

I feel like this should be a straightforward task but for whatever reason once my txn is broadcast the block explorers show UNKNOWN rather than the OP_RETURN. runes protocol aside, i should be able to use an OP_RETURN with any data following it, right?

Here is some sample code
```js
var payload = hexToBytes( '148dde9d011427' );
var rune   = [ 'OP_RETURN', 'OP_13', payload ]
var runestone = Script.encode(rune);
```

i then add `runestone` as the scriptpubkey of a 0 value txn output. the txn signs and broadcasts no problem.

here are some examples on testnet that shown UNKNOWN
* https://mempool.space/testnet/tx/021c2d43e4ec4d177505ee791eb1af242568d87fc2bef7725cc8745ed3f4d05c
* https://mempool.space/testnet/tx/56679d04c606290fbc0b268810ea0f0a90045e79b33d8ee27ae1cbb612a5b03a

It should look something like the OP_RETURN here. 
* https://mempool.space/testnet/tx/07ddd254e863af3744597007074189245211539cf6969b1d77f4043f37630885

any thoughts appreciated!

**Comment by skyrover7** [comment]
yea so i didn't need to script.encode, just directly put the script in the txn and it worked!

**Comment by cmdruid** [comment]
Yeah the transaction encoder should also handle encoding any scripts that you have in the transaction, so you don't have to encode them separately.

**Comment by cmdruid** [comment]
I haven't done any runes stuff yet, but if you want to add an OP_RETURN output to your transaction, it should look something like this:

```ts
const vout = [{
  value        : 0,
  scriptPubKey : [ 'OP_RETURN', 'hex_data_goes_here' ]
}],
```

FYI the runes protocol stuffs data in the OP_RETURN output, but that data references other outputs in the transaction by their index, so you have to make sure that your outputs are ordered properly. OP_RETURN outputs typically are the last output in the tx.

Let me know if you have any further questions about it.

**Comment by melvincarvalho** [comment]
Thanks I did figure it out, but it took some trial and error.  That snippet will help anyone searching the repo for OP_RETURN.  Works great, thanks for the library!
