### ISSUE TITLE
sponsors?

### ISSUE THREAD

**Issue by ghost** [cmdruid/tapscript#39]

**Comment by cmdruid** [comment]
Thank you for your kind offer to donate!

I looked into Github Sponsors, and it seems to involve adding a bank account and going through KYC. Unfortunately I don't want to do any of that.

I will take bitcoin though, please feel free to donate sats here:

bitcoin : bitcoin:bc1qnx8julmud2vqdqngxw9rmuv3js67kq9rzvtmm5
lnurl   : lnurl:cmd@stacker.news

Also if there's a better way to add donations to this project without having to KYC, let me know.
