### ISSUE TITLE
Plz how to use tweaked P2TR  address to sign?

### ISSUE THREAD

**Issue by winktool** [cmdruid/tapscript#4]
https://github.com/cmdruid/tapscript/blob/master/test/example/taproot/inscribe.test.ts#L76

**Comment by cmdruid** [comment]
You can't use a tweaked tapkey to sign for an inscription. If you are doing a key-spend, there is an example located here:

https://github.com/cmdruid/tapscript/blob/master/test/example/taproot/keyspend.test.ts

**Comment by toptal126** [comment]
Dear cmdruid.
In unisat wallet, taproot address is displayed in tweaked form. How do i write a script to sign for an inscription using the tweaked tapkey? I don't mind revealing the script.
