### ISSUE TITLE
Invalid Schnorr Siganture - Example: Basic Pay-to-Pubkey Spending

### ISSUE THREAD

**Issue by arminherbsthofer** [cmdruid/tapscript#40]
Hi, when I follow the example “Basic Pay-to-Pubkey Spending” the Signature check at the end of the script returns True, however, when I submit the transaction hash to mempool.space, it tells me: non-mandatory-script-verify-flag Invalid-Schnorr-Signature.

Is the script correct? I am using testnet.

**Comment by cmdruid** [comment]
Hello. I apologize for missing this. The error "non-mandatory-script-verify-flag Invalid-Schnorr-Signature" has to do with the signature being invalid. It could also do with the sighash being invalid as well, or the key not being properly tweaked.

I would need to know more information. Please feel free to re-open this issue if you still need help.
