### ISSUE TITLE
Examples are outdated.

### ISSUE THREAD

**Issue by maxgmer** [cmdruid/tapscript#41]
Examples are outdated.
E.g. this one (https://github.com/cmdruid/tapscript/blob/master/test/example/taproot/keyspend.test.ts) uses non-existent methods from "util".

Maybe you already know, would be awesome if you updated those.
Thanks in advance!

**Comment by cmdruid** [comment]
I plan to update these very soon, with actual integration testing using bitcoin core. I already have it running in another branch.

Stay tuned! :-)

**Comment by maxgmer** [comment]
That's awesome! I'm closing this issue then.
