### ISSUE TITLE
Question: Is it possible for a reveal transaction to not be valid?

### ISSUE THREAD

**Issue by maxgmer** [cmdruid/tapscript#42]
Is it possible for a reveal transaction to not be valid, if the funding transaction went through (meaning the secret key is correct)? Provided the funding transaction was made from the same secret key.

**Comment by cmdruid** [comment]
The funding tx is committing to a locking script (that reveals the inscription in this case), but the funding tx does not validate if the locking script is constructed correctly. 

So if there is something incorrect about the locking script, then the output may not be spendable, or it may not be recognized as an inscription from ord.

But if the locking script is correct (and includes a public key for spending), then the public key should be able to spend the inscription utxo and reveal it at any time.

**Comment by maxgmer** [comment]
@cmdruid thank you!
I use the script from the examples without anything custom, so I should be good then.
