### ISSUE TITLE
Question: Order of inputs in a transaction.

### ISSUE THREAD

**Issue by maxgmer** [cmdruid/tapscript#45]
The way address spending works is:
1. First inputs' sats cover the output amount.
2. Remaining inputs' sats, which didn't fit into the output amount, go to miners.

But how do I specify the order of input UTXOs with this library?
I want to make sure inscription UTXOs are first, while ordinary sats are last, so that inscriptions don't leak to miners.

**Comment by cmdruid** [comment]
When you create a `TxData` object, the `vin` and `vout` are arrays, and the order of items in that array is the order in which they will be encoded when you convert the transaction data into hex.

**Comment by maxgmer** [comment]
@cmdruid I see, thanks!
