### ISSUE TITLE
How can I decode script from tpubkey

### ISSUE THREAD

**Issue by sondotpin** [cmdruid/tapscript#7]
```
const script  = [ pubkey, 'OP_CHECKSIG', 'OP_0', 'OP_IF', marker, '01', mimetype, 'OP_0', imgdata, 'OP_ENDIF' ]

const tapleaf = Tap.encodeScript(script)

const [ tpubkey, cblock ] = Tap.getPubKey(pubkey, { target: tapleaf })
```

How can I decode **script** from **tpubkey**

**Comment by cmdruid** [comment]
It is not possible to decode the script. The key has a cryptographic commitment to the script, but it does not contain the script itself.

**Comment by cmdruid** [comment]
You have to publish the script in a transaction. The indexer only looks at scripts which are published. The key and address itself does not contain the content of the script.
